mysite/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pedido.urls')),
    
]

pedido/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.conf.urls import url
from pedido.views import CadastroUpdate
from pedido.views import CadastroDelete
from django.conf.urls import include

urlpatterns = [
    path('', views.CadastroListView.as_view(), name='cadastro-list'),
    url(r'(?P<pk>[0-9]+)/$', CadastroUpdate.as_view(), name='cadastro-update'),
    url(r'(?P<pk>[0-9]+)/delete/$', CadastroDelete.as_view(), name='cadastro-delete'),
    path('cadastrar', views.index, name='index'),
    path('ajax/load-preco/', views.load_preco, name='load_preco'),
    path('ajax/load-rentabilidade/', views.load_rentabilidade, name='load_rentabilidade'),
    path('ajax/load-total/', views.load_total, name='load_total'),

]

pedido/models.py
from django.urls import reverse
from django.db import models
from django.db import models
from django import forms


# Create your models here.
class Cliente(models.Model):
    nome= models.CharField(max_length=200)
    def __str__(self):
        return str(self.nome)

class Produto(models.Model):
    nome= models.CharField(max_length=200,blank=False, null=False)
    preco_unit = models.FloatField(max_length=200)
    multiplo = models.IntegerField(default=0, null=False)
    def __str__(self):
        return '{} '.format(self.nome)

class Cadastro(models.Model):
    cliente = models.ForeignKey('Cliente',on_delete=models.CASCADE, null=False, blank=False)
    item = models.ForeignKey('Produto',on_delete=models.CASCADE,null=False, blank=False)
    preco_unitario =models.FloatField(default=0)
    quantidade = models.IntegerField(default=0)
    total = models.FloatField(null=False, default=0)
    def __str__(self):
      return '{} - {}'.format(self.cliente.nome, self.item.nome)
    def get_absolute_url(self):
      return reverse('cadastro-update', kwargs={'pk': self.pk})

pedido/forms.py
from django import forms
from .models import Cadastro
from .models import Produto

class CadastroForm(forms.ModelForm):
    class Meta:
        model = Cadastro
        fields = ['cliente', 'item', 'preco_unitario', 'quantidade', 'total']

    def clean(self):        
        item = self.cleaned_data['item']
        quantidade = self.cleaned_data['quantidade']
        preco_unitario = self.cleaned_data['preco_unitario']
        if preco_unitario <= 0:
            raise forms.ValidationError("O preço precisa ser maior que 0!")
        if quantidade <= 0:
            raise forms.ValidationError("A quantidade precisa ser maior que 0!")
        if ((preco_unitario) < ((item.preco_unit)*0.9)):
            raise forms.ValidationError("Rentabilidade ruim!")
        if (item.multiplo) > 0:
            if (quantidade % (item.multiplo)) !=0:
               raise forms.ValidationError("A quantidade precisa multipla de: %s" %(item.multiplo))
        return self.cleaned_data

pedido/views.py
from django.shortcuts import render
from .forms import CadastroForm
from .forms import Cadastro
from .forms import Produto
from django.contrib import messages
from django.utils import timezone
from django.views.generic.list import ListView
from django.views import generic
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib import messages

def base(request):
    return render(request, "pedido/base.html")
def index(request):
    if request.method=='POST':
        form = CadastroForm(request.POST or None)
        if form.is_valid():
            messages.success(request, 'Enviado com sucesso!')
            form.save()
    else:
        form = CadastroForm()
    context = {'form': form}
    return render(request, "pedido/index.html", context)

class CadastroListView(ListView):
    model = Cadastro
    template_name = "pedido/base.html"

    def get_context_data(self, **kwargs):
        context = super(CadastroListView, self).get_context_data(**kwargs)
        return context
class CadastroUpdate(UpdateView):
    model = Cadastro
    form_class = CadastroForm
    template_name="pedido/index.html"
    success_url = ('/')
class CadastroDelete(DeleteView):
    model = Cadastro
    success_url = reverse_lazy('pedido/base.html')
def load_preco(request):
    item = request.GET.get('item')
    produto = Produto.objects.get(id=item)
    return JsonResponse({'preco_unitario' : produto.preco_unit})
def load_rentabilidade(request):
    item = request.GET.get('item')
    preco_unitario = request.GET.get('preco_unitario')
    produto = Produto.objects.get(id=item)
    data={
        'rent_otima': (float(preco_unitario) > produto.preco_unit),
        'rent_boa': (float(preco_unitario) >= (produto.preco_unit*0.9))
                        and (float(preco_unitario)<= (produto.preco_unit)),
    }
    return JsonResponse(data)
def load_total(request):
    quantidade = request.GET.get('quantidade')
    preco_unitario = request.GET.get('preco_unitario')
    data={
        'total': (float(quantidade) * float(preco_unitario)),
    }
    return JsonResponse(data)

pedido/templates/pedido/base.html
{% load staticfiles %}
{{ form.media.css }}
{{ form.media.js }}
<html>
    <head>
        <title>Mercos</title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/pedido.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </head>
    <body style="background-color:#e6f3ff;">
        <div class="page-header">
            <h1 align="center" color=#9900ff><a href="/">Pedidos</a></h1>
        </div>

        <div>
          <h2 style="background-color: #b3daff;color:#339cff; height:50px; " align="center">Lista de Cadastros</h2>
          {% if object_list != None %}

                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col">Editar</th>
                      <th scope="col">ID</th>
                      <th scope="col">Cliente</th>
                      <th scope="col">Item</th>
                      <th scope="col">Preco Unitario</th>
                      <th scope="col">Quantidade</th>
                      <th scope="col">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for cadastro in object_list %}
                    <tr>

                      <td><a href="/{{ cadastro.id }}/"><i class="far fa-edit"></i></a></td>
                      <td>{{cadastro.id}}</td>
                      <td>{{cadastro.cliente}}</td>
                      <td>{{cadastro.item}}</td>
                      <td> {{cadastro.preco_unitario}} </td>
                      <td> {{cadastro.quantidade}}</td>
                      <td> {{cadastro.total}}</td>
                    </tr>
                  </tbody>
                </tr>
                {% endfor %}
          {% else %}
              <p>Nenhum cadastro foi feito ainda.</p>
          {% endif %}
      </table>


         </table>
       </div><br> <br>
       <div class="content">
         <a href="{% url 'index' %}"><input style="position:absolute; right: 200px;" type =button value='Cadastrar'></a>
       </div>
    </body>
</html>

pedido/templates/pedido/index.html
{% load staticfiles %}
{{ form.media.css }}
{{ form.media.js }}
<html>
    <head>
        <title>Pedidos Mercos</title>


        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/pedido.css' %}">
    </head>
    <body style="background-color:#e6f3ff;">
      <div class="page-header">
            <h1  align="center" ><a  href="{% url 'index' %}">Cadastro</a></h1>
      </div>

      <div class="row align-items-center">
        <form id="CadastroForm" method ='POST' data-url="{% url 'load_preco' %}" novalidate> {% csrf_token %}
          <table align=center>
            {{ form.as_table }}
          </table>

           {% if messages %}
            {% for message in messages %}
              <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
           {% endif %}

           <input type='submit' style="position:absolute; right: 520px;" value='Enviar'/>
           <a href="{% url 'index' %}"><input style="position:absolute; left: 490px;" type =button value='Novo'  ></a>
           <br><br><br><br><br><br><br><br><br><br>
           <a href="/"><input type =button value='Voltar'  ></a>


       </form>
     </div>

     <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
     <script>
        $("#id_item").change(function () {
            var url = $("#CadastroForm").attr("data-url");
            console.log('URL ',url)
            var item = $(this).val();
            $.ajax({
              url: url,
              data: {
                'item': item
              },
              dataType: 'json',
              success: function (data) {
                $('#id_preco_unitario').val(data['preco_unitario'])
              }
            });
          });
        </script>
        <script>
          $("#id_preco_unitario").change(function () {
            var preco_unitario = $(this).val();
            var item = $("#id_item").val();
            $.ajax({
              url: '/ajax/load-rentabilidade/',
              data: {
                'item': item,
                'preco_unitario': preco_unitario
              },
              dataType: 'json',
              success: function (data) {
                if (data.rent_otima) {
                  alert("Rentabilidade ótima.");
                }
                if (data.rent_boa){
                  alert("Rentabilidade boa.");
                }
              }
            });
          });
        </script>
        <script>
          $("#id_quantidade").change(function () {
            var quantidade = $(this).val();
            var preco_unitario= $("#id_preco_unitario").val();
            $.ajax({
              url: '/ajax/load-total/',
              data: {
                'quantidade': quantidade,
                'preco_unitario': preco_unitario
              },
              dataType: 'json',
              success: function (data) {
                $('#id_total').val(data['total'])
              }
            });
          });
        </script>
  </body>
</html>